<?php
/** * Enqueue scripts and styles. */
function your_theme_scripts()
{ wp_enqueue_style( 'style', get_stylesheet_uri() ); }
add_action( 'wp_enqueue_scripts','your_theme_scripts' );



// this theme has one menu location
register_nav_menu('primary', 'primary menu horizontal' );



//I decided to remore the more tag generated by the_excerpt and manualy add link to each post
//I did this because exceprt more is not run on posts that have a manual more tag
function wpdocs_excerpt_more( $more){
  return '';
}
add_filter('excerpt_more','wpdocs_excerpt_more');

//add Thumbnail support
add_theme_support('post-thumbnails');
set_post_thumbnail_size(300,450);

//Thumnail size
add_image_size('custom-thumb-200',200,350,true);
add_image_size('custom-thumb-300',300,450,true);
add_image_size('custom-thumb-600',600,900,true);
add_image_size('custom-thumb-800',800,1100,false);

//add widget area functionality
add_action('widgets_init','mytheme_widgets_init');
function mytheme_widgets_init()
{ $args = array(
  'name' => __('sidebar1'),
  'id'   => 'sidebar1',
  'description' => 'this is my sidebar',
  'class' => 'sidebarclass',
  'before_widget' => '<div>', //note we have used section rather than the default li
  'after_widget' => '</div>',
  'before_title' => '<h3>', //use h3 tag to match html design
  'after_title' => '</h3>'  );
  register_sidebar( $args );
}

add_action('widgets_init','mytheme_widgets_init2');
function mytheme_widgets_init2()
{ $args2 = array(
  'name' => __('sidebar2'),
  'id'   => 'sidebar2',
  'description' => 'this is my footer',
  'class' => 'sidebarclass',
  'before_widget' => '<div>', //note we have used section rather than the default li
  'after_widget' => '</div>',
  'before_title' => '<h3>', //use h3 tag to match html design
  'after_title' => '</h3>'  );
  register_sidebar( $args2 );
}
add_action('widgets_init','mytheme_widgets_init3');
function mytheme_widgets_init3()
{ $args3 = array(
  'name' => __('sidebar3'),
  'id'   => 'sidebar3',
  'description' => 'this is my footer',
  'class' => 'sidebar',
  'before_widget' => '<div class="col-xs-12">', //note we have used section rather than the default li
  'after_widget' => '</div>',
  'before_title' => '<h3>', //use h3 tag to match html design
  'after_title' => '</h3>'  );
  register_sidebar( $args3 );
}
add_action('widgets_init','mytheme_widgets_init4');
function mytheme_widgets_init4()
{ $args4 = array(
  'name' => __('sidebar4'),
  'id'   => 'sidebar4',
  'description' => 'this is my footer',
  'class' => 'sidebarclass',
  'before_widget' => '<div>', //note we have used section rather than the default li
  'after_widget' => '</div>',
  'before_title' => '<h3>', //use h3 tag to match html design
  'after_title' => '</h3>'  );
  register_sidebar( $args4 );
}

/* Bones Custom Post Type Example
This page walks you through creating
a custom post type and taxonomies. You
can edit this one or copy the following code
to create another one.

I put this in a separate file so as to
keep it organized. I find it easier to edit
and change things if they are concentrated
in their own file.

Developed by: Eddie Machado
URL: http://themble.com/bones/
*/

// Flush rewrite rules for custom post types
add_action( 'after_switch_theme', 'review_rewrite_rules' );

// Flush your rewrite rules
function review_rewrite_rules() {
  flush_rewrite_rules();
}

// let's create the function for the custom type
function review_example() {
  // creating (registering) the custom type
  register_post_type( 'review', /* (http://codex.wordpress.org/Function_Reference/register_post_type) */
    // let's now add all the options for this post type
    array( 'labels' => array(
      'name' => __( 'review', 'thebookreview' ), /* This is the Title of the Group */
      'singular_name' => __( 'review post', 'thebookreview' ), /* This is the individual type */
      'all_items' => __( 'All review', 'thebookreview' ), /* the all items menu item */
      'add_new' => __( 'Add New', 'thebookreview' ), /* The add new menu item */
      'add_new_item' => __( 'Add New review', 'thebookreview' ), /* Add New Display Title */
      'edit' => __( 'Edit', 'thebookreview' ), /* Edit Dialog */
      'edit_item' => __( 'Edit review', 'thebookreview' ), /* Edit Display Title */
      'new_item' => __( 'New review', 'thebookreview' ), /* New Display Title */
      'view_item' => __( 'View review', 'thebookreview' ), /* View Display Title */
      'search_items' => __( 'Search review', 'thebookreview' ), /* Search Custom Type Title */
      'not_found' =>  __( 'Nothing found in the Database.', 'thebookreview' ), /* This displays if there are no entries yet */
      'not_found_in_trash' => __( 'Nothing found in Trash', 'thebookreview' ), /* This displays if there is nothing in the trash */
      'parent_item_colon' => ''
      ), /* end of arrays */
      'description' => __( 'This is the example review', 'thebookreview' ), /* Custom Type Description */
      'public' => true,
      'publicly_queryable' => true,
      'exclude_from_search' => false,
      'show_ui' => true,
      'query_var' => true,
      'menu_position' => 8, /* this is what order you want it to appear in on the left hand side menu */
      'menu_icon' => 'dashicons-format-chat', /* the icon for the custom post type menu */
      'rewrite'	=> array( 'slug' => 'review', 'with_front' => false ), /* you can specify its url slug */
      'has_archive' => 'review', /* you can rename the slug here */
      'capability_type' => 'post',
      'hierarchical' => false,
      /* the next one is important, it tells what's enabled in the post editor */
      'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'trackbacks', 'custom-fields', 'comments', 'revisions', 'sticky')
    ) /* end of options */
  ); /* end of register post type */

  // /* this adds your post categories to your custom post type */
  // register_taxonomy_for_object_type( 'category', 'review' );
  // /* this adds your post tags to your custom post type */
  // register_taxonomy_for_object_type( 'post_tag', 'review' );

}

  // adding the function to the Wordpress init
  add_action( 'init', 'review_example');

  /*
  for more information on taxonomies, go here:
  http://codex.wordpress.org/Function_Reference/register_taxonomy
  */

  // now let's add review categories (these act like categories)
  register_taxonomy( 'custom_cat',
    array('review'), /* if you change the name of register_post_type( 'custom_type', then you have to change this */
    array('hierarchical' => true,     /* if this is true, it acts like categories */
      'labels' => array(
        'name' => __( 'review categories', 'thebookreview' ), /* name of the custom taxonomy */
        'singular_name' => __( 'review category', 'thebookreview' ), /* single taxonomy name */
        'search_items' =>  __( 'Search review categories', 'thebookreview' ), /* search title for taxomony */
        'all_items' => __( 'All review categories', 'thebookreview' ), /* all title for taxonomies */
        'parent_item' => __( 'Parent review category', 'thebookreview' ), /* parent title for taxonomy */
        'parent_item_colon' => __( 'Parent review category:', 'thebookreview' ), /* parent taxonomy title */
        'edit_item' => __( 'Edit review category', 'thebookreview' ), /* edit custom taxonomy title */
        'update_item' => __( 'Update review category', 'thebookreview' ), /* update title for taxonomy */
        'add_new_item' => __( 'Add New review category', 'thebookreview' ), /* add new title for taxonomy */
        'new_item_name' => __( 'New review category Name', 'thebookreview' ) /* name title for taxonomy */
      ),
      'show_admin_column' => true,
      'show_ui' => true,
      'query_var' => true,
      'rewrite' => array( 'slug' => 'custom-slug' ),
    )
  );

  // now let's add review tags (these act like categories)
  register_taxonomy( 'custom_tag',
    array('review'), /* if you change the name of register_post_type( 'custom_type', then you have to change this */
    array('hierarchical' => false,    /* if this is false, it acts like tags */
      'labels' => array(
        'name' => __( 'review tags', 'thebookreview' ), /* name of the custom taxonomy */
        'singular_name' => __( 'review tag', 'thebookreview' ), /* single taxonomy name */
        'search_items' =>  __( 'Search review tags', 'thebookreview' ), /* search title for taxomony */
        'all_items' => __( 'All review tags', 'thebookreview' ), /* all title for taxonomies */
        'parent_item' => __( 'Parent review tag', 'thebookreview' ), /* parent title for taxonomy */
        'parent_item_colon' => __( 'Parent review tag:', 'thebookreview' ), /* parent taxonomy title */
        'edit_item' => __( 'Edit review tag', 'thebookreview' ), /* edit custom taxonomy title */
        'update_item' => __( 'Update review tag', 'thebookreview' ), /* update title for taxonomy */
        'add_new_item' => __( 'Add New review tag', 'thebookreview' ), /* add new title for taxonomy */
        'new_item_name' => __( 'New review tag Name', 'thebookreview' ) /* name title for taxonomy */
      ),
      'show_admin_column' => true,
      'show_ui' => true,
      'query_var' => true,
    )
  );

  /**
   * Filter the except length to 20 characters.
   *
   * @param int $length Excerpt length.
   * @return int (Maybe) modified excerpt length.
   */
  function wpdocs_custom_excerpt_length( $length ) {
      return 15;
  }
  add_filter( 'excerpt_length', 'wpdocs_custom_excerpt_length', 999 );



?>
